__version__ = "1.9.9"
__author__ = "Domingo E. Savoretti"
__email__ = "esavoretti@gmail.com"
__license__ = "MIT"
__url__ = "https://github.com/sandy98/pybase3"
__description__ = "A simple library to read and write dbase III files."
